# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wwsUYDy3c34yPssS7P9DRqUtrsg-zX8g
"""



class Calculator:
    def __init__(self, numberList):
        self.numberList = numberList 

    def sum(self):
        result = 0
        for num in self.numberList:
            result += num
        return result 

    def avg(self):
        total = self.sum()
        return total / len(self.numberList)